# Generated by Django 4.2.30 on 2026-08-19 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0004_shared_tracking_steps'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='build_year',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='shipment',
            name='car_brand',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name='ShipmentDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='shipment_docs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='tracking.shipment')),
            ],
        ),
    ]
