# Generated by Django 4.2.30 on 2026-08-19 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0005_shipment_build_year_shipment_car_brand_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='customer_name',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
