# Generated by Django 4.2.30 on 2026-08-28 21:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0007_shipment_stage_dates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminuser',
            name='phone_number',
            field=models.CharField(max_length=16, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid Iranian phone number (11 digits starting with 0 or 10 digits starting with 9).', regex='^(0\\d{10}|9\\d{9})$')]),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='completed_steps',
            field=models.PositiveSmallIntegerField(choices=[(0, 'هیچ مرحله\u200cای تکمیل نشده'), (1, 'تحویل و بارگیری در پورت راشد (دبی)'), (2, 'در مسیر ترانزیت دریایی'), (3, 'ورود به بندر مقصد (در انتظار تخلیه)'), (4, 'تخلیه کامل و ترخیص از شناور'), (5, 'بارگیری و انتقال با خودروبَر به مقصد')], default=0),
        ),
    ]
