# Generated by Django 5.0

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Inquiry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("manufacturing_year", models.PositiveSmallIntegerField()),
                ("model", models.CharField(max_length=100)),
                ("color", models.CharField(max_length=50)),
                ("paint_section", models.CharField(max_length=100)),
                (
                    "chassis_number",
                    models.CharField(max_length=100, unique=True),
                ),
                (
                    "transmission",
                    models.CharField(
                        choices=[
                            ("manual", "Manual"),
                            ("automatic", "Automatic"),
                        ],
                        max_length=20,
                    ),
                ),
                ("mileage", models.PositiveIntegerField()),
                ("requester_name", models.CharField(max_length=150)),
                ("contact_number", models.CharField(max_length=30)),
                ("email", models.EmailField(max_length=254)),
            ],
        ),
    ]
