# Generated by Django 5.0 on 2026-08-16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("inquiries", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="inquiry",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="inquiry",
            name="delivery_status",
            field=models.CharField(
                choices=[
                    ("request_received", "Request received"),
                    ("vehicle_inspection", "Vehicle inspection"),
                    ("purchased", "Purchased"),
                    ("in_transit", "In transit"),
                    ("customs_clearance", "Customs clearance"),
                    ("ready_for_delivery", "Ready for delivery"),
                    ("delivered", "Delivered"),
                    ("cancelled", "Cancelled"),
                ],
                db_index=True,
                default="request_received",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="inquiry",
            name="requested_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="inquiries",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="inquiry",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                default=django.utils.timezone.now,
            ),
            preserve_default=False,
        ),
        migrations.AlterModelOptions(
            name="inquiry",
            options={"ordering": ("-created_at",)},
        ),
    ]
